/**
 * Client Component Registry
 *
 * This file will be auto-generated by the build process
 * For now, it's a placeholder to allow compilation
 *
 * TODO: Generate this file during build from scanned components
 */

import type { ClientComponentRegistry } from '../serialization/types'

// Empty registry for now
// Will be populated by registry-builder during build
export const clientComponentRegistry: ClientComponentRegistry = {}
